fix bug in xml output

diff --git a/bin/shiot-xunit b/bin/shiot-xunit
--- a/bin/shiot-xunit
+++ b/bin/shiot-xunit
@@ -24,8 +24,9 @@ testcases()
 
 runtest()
 {
-	declare tf="$1" tmpf="$2" outf="$3"
+	declare tf="$1" outf="$2"
 	declare xstat
+	declare tmpf="$LOGDIR/sx-$$.tmp"
 
 	$DFLAG && echo "+ shiot -C $t"
 
@@ -36,11 +37,12 @@ runtest()
 
 	if $OFLAG; then
 		{
+		# output the testcase record for this testcase
 		printf '<testcase classname="%s" name="%s" time="%d">\n' \
 			"shiot" "$t" "$SECONDS"
 		if [ $xstat -ne 0 ]; then
-			printf '</failure>\n'
-			cat "$outf"
+			printf '<failure>\n'
+			cat "$tmpf"
 			printf '</failure>\n'
 		fi
 		printf '</testcase>\n'
@@ -55,7 +57,7 @@ runsuite()
 	declare name="$1"
 	declare cases=$(testcases "$name" | sort)
 	declare tests=0 errors=0 failures=0
-	declare outf tmpf
+	declare outf="$LOGDIR/xml.tmp"
 	declare xstat
 
 	if [ -z "$cases" ]; then
@@ -70,9 +72,7 @@ runsuite()
 	mkdir -p $LOGDIR
 
 	for t in $cases; do
-		outf="$LOGDIR/$tests.out"
-		tmpf="$LOGDIR/$tests.tmp"
-		if ! runtest "$t" "$tmpf" "$outf"; then
+		if ! runtest "$t" "$outf"; then
 			FAILED=1
 			((failures++))
 		fi
@@ -83,11 +83,7 @@ runsuite()
 	{
 	printf '<testsuite name="%s" tests="%d" errors="%d" failures="%d">\n' \
 		"$name" "$tests" "$errors" "$failures"
-	((i=0))
-	for t in $cases; do
-		cat "$LOGDIR/$i.out"
-		((i++))
-	done
+	cat "$outf"
 	printf '</testsuite>\n'
 	} >> $XMLFILE
 	fi
